function component = field_AdapterTo_ContinuesFieldFunction(componentOfField, typeOfCylinder, r, z, q, p, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m,...
          a_p_field_1_forw, psi_forward_1, B_1_forward_1,B_2_forward_1,Cm2_forward_1,  Dm2_forward_1)
      
      if(real(sum(p)) > 0 || imag(sum(p)) < 0 )
          component = field__ForBesselBeamRepresentation_Continues_discreteRepr(componentOfField, typeOfCylinder,r, q, 0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, 0, 0,...
              a_p_field_1_forw, 0, 0, 0,...
              psi_forward_1, 0, 0, 0,...
              0, 0, 0, 0,...
              B_1_forward_1,B_2_forward_1,Cm2_forward_1,  Dm2_forward_1,...
              0,0,0, 0,...
              0,0,0, 0,...
              0,0,0, 0);
      else
          component = field__ForBesselBeamRepresentation_Continues_discreteRepr(componentOfField, typeOfCylinder,r, q, 0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, 0, 0,...
              0, a_p_field_1_forw, 0, 0,...
              0, psi_forward_1, 0, 0,...
              0, 0, 0, 0,...
              0,0,0, 0,...
              B_1_forward_1,B_2_forward_1,Cm2_forward_1,  Dm2_forward_1,...
              0,0,0, 0,...
              0,0,0, 0);
      end
