%%%%%% representation of field of bessel beams E and H polarized in the
%%%%%% case there cylinder is ideal conductivity
clear all
tic
systemParameters

%%%%%% paramters of beam
% m = 1;
p_0 = 1/sqrt(2);
q_0 = sqrt(1-p_0^2);
q_0 = q_0.* (2*(imag(q_0) <= 0)-1);

% %%%%%% paramenter of cylinder for perfect conductivity core
% a_0 = 2.4048./ (k_0 * q_0);%%% radius of inner core
% % a_0 = 5.1356./ (k_0 * q_0);%%% radius of inner core for m=2
% % a_0 = (3.8317)./ (k_0 * q_0);%%% radius of inner core
% 
% a_0 = 4.330161354189217;
% k_0 = 0.541270169273652 * (2*pi) / a_0;
% % k_0 = 0.2 * (2*pi) / a_0;
% k_0 = 1.4787 * (2*pi) / a_0;


% p_0 = 1.5514
% p_0 = 1-0.1;
q_0 = sqrt(1-p_0^2);
q_0 = q_0.* (2*(imag(q_0) <= 0)-1);

typeOfCylinder = 'Gyrotropic';
% typeOfCylinder = 'Isotropic';
% typeOfCylinder = 'PerfectConductivity';

upper_Bound = 20;
N = 1600;
[dq_simp, q_back, p] = quadratureMethod_forIntegralEqs('simpson', N, q_0, 1e-8, upper_Bound);
% [dq_simp, q_back, p_cs] = quadratureMethod_forIntegralEqs('difficult_simpsonMarkovGildendurgExp', N, 1i, 1e-7, upper_Bound);


p_back = sqrt(1 - q_back.^2);
p_back = p_back.* (2*(imag(p_back) <= 0)-1);
% p_back = real(p_back) - 1i * abs(imag(p_back));
    
%%%%% the coefficient of forward waves in waveguend space
q = q_back;
p = p_back;

rho = [0.12:0.1:10] * a_0;
% rho = [0.4:0.02:5] * a_0;
% rho = [0.1:0.5:35] * a_0;
% rho = [0.12:0.1:20] *a_0;
% rho = [0.99:0.01:1.01] *a_0;

%%%%%%%%%%%%%%%%%%%%%%% E-polarized beam %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  AE_0 = 1;
  Ez_inc    = AE_0.* (besselj(m, k_0.* rho * q_0)); 
  dEz_q_inc = AE_0.* k_0.* (q_0).*((besselj(m,   k_0.* rho* q_0) * (m))./ (k_0.* rho* q_0)  - besselj(m + 1,   k_0.* rho* q_0));

%%%%%%%%%%%%%%%%%%%%%%% H-polarized beam %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  AH_0 = 0;
  Hz_inc    = AH_0.* (besselj(m, k_0.* rho * q_0));
  dHz_q_inc = AH_0.* k_0.* (q_0).*((besselj(m,   k_0.* rho* q_0) * (m))./ (k_0.* rho* q_0)  - besselj(m + 1,   k_0.* rho* q_0));
  
 %%%%%%%%%%%%%%%%%%%%%%% other field components of the beam %%%%%%%%%%%%%%%
  A0 = 1./ (k_0 * (1 - p_0.^2));
  Ephi_inc  = A0.* ((-p_0.* (m./rho)).* Ez_inc + 1i * dHz_q_inc);
  Hphi_inc  = A0.* (-1i * dEz_q_inc - (p_0.* (m./rho)).* Hz_inc);
  Hrho_inc  = A0.* ((m./rho).* Ez_inc - 1i * p_0.* dHz_q_inc);
  Erho_inc  = A0.* (-1i * p_0.* dEz_q_inc - (m./rho).* Hz_inc);
  
  %%%%%%%%%%%%%%%%%%%%% painting of field %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  plot_all_field_components(3, rho, a_0, '-', 2, Ez_inc, Ephi_inc, Erho_inc, Hz_inc, Hphi_inc, Hrho_inc)



%%%%%%%%%%%%%%%%%%%%%%% calculation of field reperesentation %%%%%%%%%%%%%%

z = 0;
%%%%%%%%%%%%%%%%%%%% E-polarized beam %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% add delta function %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Ez_repres   = field_ForBesselBeamRepresentation_deltaFunction('Ez', typeOfCylinder, rho, q_0, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);
Ephi_repres = field_ForBesselBeamRepresentation_deltaFunction('Ephi', typeOfCylinder, rho, q_0, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);
Erho_repres = field_ForBesselBeamRepresentation_deltaFunction('Erho', typeOfCylinder, rho, q_0, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);
Hz_repres   = field_ForBesselBeamRepresentation_deltaFunction('Hz', typeOfCylinder, rho, q_0, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);
Hphi_repres = field_ForBesselBeamRepresentation_deltaFunction('Hphi', typeOfCylinder, rho, q_0, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);
Hrho_repres = field_ForBesselBeamRepresentation_deltaFunction('Hrho', typeOfCylinder, rho, q_0, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);

% plot_all_field_components(3, rho, a_0, '-*', 1, Ez_repres, Ephi_repres, Erho_repres, Hz_repres, Hphi_repres, Hrho_repres)

%%%%%%%%%%%%%% propagation constants of eigenwaves %%%%%%%%%%%%%%%%%%%%%%%%
if(strcmp(typeOfCylinder, 'Isotropic'))
    p_n__of_descreteMode_of_isotropicCyl
elseif(strcmp(typeOfCylinder, 'Gyrotropic'))
    p_n__of_descreteMode_of_gyrotropicCyl
%     p_n = p_n(1:20);
    p_n(7:end) = -p_n(7:end);
end

%%%%%%%%%%%%%%%%%% add discrete modes %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    q_n = sqrt(1-p_n.^2);
    q_n = q_n.* (2*(imag(q_n) <= 0)-1);
    
%  Ephi_repres = Ephi_repres*0;
%  Hphi_repres = Hphi_repres*0; 
    for in=1:size(p_n,1)
        Ez_repres = Ez_repres +...
            field_of_discreteMode__ForBesselBeamRepresentation('Ez', typeOfCylinder, rho, q_n(in), p_n(in),...
            q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);
        Hz_repres = Hz_repres +...
            field_of_discreteMode__ForBesselBeamRepresentation('Hz', typeOfCylinder, rho, q_n(in), p_n(in),...
            q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);
        Ephi_repres = Ephi_repres +...
            field_of_discreteMode__ForBesselBeamRepresentation('Ephi', typeOfCylinder, rho, q_n(in), p_n(in),...
            q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);
        Erho_repres = Erho_repres +...
            field_of_discreteMode__ForBesselBeamRepresentation('Erho', typeOfCylinder, rho, q_n(in), p_n(in),...
            q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);  
        Hphi_repres = Hphi_repres +...
            field_of_discreteMode__ForBesselBeamRepresentation('Hphi', typeOfCylinder, rho, q_n(in), p_n(in),...
            q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);
        Hrho_repres = Hrho_repres +...
            field_of_discreteMode__ForBesselBeamRepresentation('Hrho', typeOfCylinder, rho, q_n(in), p_n(in),...
            q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);
    end
    
% plot_all_field_components(3, rho, a_0, '-*', 1, Ez_repres, Ephi_repres, Erho_repres, Hz_repres, Hphi_repres, Hrho_repres)





[a_p_field_1_forw, a_p_field_1_back, a_p_field_2_forw, a_p_field_2_back,...
          psi_forward_1, psi_backward_1, psi_forward_1_transp, psi_backward_1_transp,...
          psi_forward_2, psi_backward_2, psi_forward_2_transp, psi_backward_2_transp,...
          B_1_forward_1,B_2_forward_1,Cm2_forward_1,  Dm2_forward_1,...
          B_1_backward_1,B_2_backward_1,Cm2_backward_1, Dm2_backward_1,...
          B_1_forward_2,B_2_forward_2,Cm2_forward_2,  Dm2_forward_2,...
          B_1_backward_2,B_2_backward_2,Cm2_backward_2, Dm2_backward_2] =...
          coeffsOfFieldAndExcitationCoeffs_of_Continues_discreteRepr(typeOfCylinder, q, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);
% m=-1;   
% [a_p_field_1_forw, a_p_field_1_back, a_p_field_2_forw, a_p_field_2_back,...
%           psi_forward_1, psi_backward_1, psi_forward_1_transp, psi_backward_1_transp,...
%           psi_forward_2, psi_backward_2, psi_forward_2_transp, psi_backward_2_transp,...
%           B_1_forward_1,B_2_forward_1,Cm2_forward_1,  Dm2_forward_1,...
%           B_1_backward_1,B_2_backward_1,Cm2_backward_1, Dm2_backward_1,...
%           B_1_forward_2,B_2_forward_2,Cm2_forward_2,  Dm2_forward_2,...
%           B_1_backward_2,B_2_backward_2,Cm2_backward_2, Dm2_backward_2] =...
%           coeffsOfFieldAndExcitationCoeffs_of_Continues_discreteRepr(typeOfCylinder, q, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0);
 
% a_p_field_2_forw = a_p_field_2_forw * 0;
%  a_p_field_1_back = a_p_field_1_back*0;
%  a_p_field_2_back = a_p_field_2_back*0;
%%%%%% test sum Hphi
% for iq = 1:size(q,2)
%     Hphi_repres = zeros(1,size(rho, 2));
%     for ir = 1:size(rho,2)
%         Hphi_repres(ir) = Hphi_repres(ir) +...
%             k_0 * (dq_simp(iq).* field__ForBesselBeamRepresentation_Continues_discreteRepr('Hphi', typeOfCylinder,...
%                   rho(ir), q(iq), q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0,...
%           a_p_field_1_forw(iq), a_p_field_1_back(iq), a_p_field_2_forw(iq), a_p_field_2_back(iq),...
%           psi_forward_1(iq), psi_backward_1(iq), psi_forward_1_transp(iq), psi_backward_1_transp(iq),...
%           psi_forward_2(iq), psi_backward_2(iq), psi_forward_2_transp(iq), psi_backward_2_transp(iq),...
%           B_1_forward_1(iq),B_2_forward_1(iq),Cm2_forward_1(iq),  Dm2_forward_1(iq),...
%           B_1_backward_1(iq),B_2_backward_1(iq),Cm2_backward_1(iq), Dm2_backward_1(iq),...
%           B_1_forward_2(iq),B_2_forward_2(iq),Cm2_forward_2(iq),  Dm2_forward_2(iq),...
%           B_1_backward_2(iq),B_2_backward_2(iq),Cm2_backward_2(iq), Dm2_backward_2(iq)));
%     end
%       figure(235)
%       hold on
%       plot(rho/a_0, real(Hphi_repres), 'bo-', rho/a_0, imag(Hphi_repres), 'ro-')
%       hold off
%  end


%  a_p_field_1_back = a_p_field_1_back*0;
%  a_p_field_2_back = a_p_field_2_back*0;
for ir = 1:size(rho,2)
    Ez_repres(ir) = Ez_repres(ir) +...
              k_0 * sum(dq_simp.* field__ForBesselBeamRepresentation_Continues_discreteRepr('Ez', typeOfCylinder,...
                  rho(ir), q, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0,...
          a_p_field_1_forw, a_p_field_1_back, a_p_field_2_forw, a_p_field_2_back,...
          psi_forward_1, psi_backward_1, psi_forward_1_transp, psi_backward_1_transp,...
          psi_forward_2, psi_backward_2, psi_forward_2_transp, psi_backward_2_transp,...
          B_1_forward_1,B_2_forward_1,Cm2_forward_1,  Dm2_forward_1,...
          B_1_backward_1,B_2_backward_1,Cm2_backward_1, Dm2_backward_1,...
          B_1_forward_2,B_2_forward_2,Cm2_forward_2,  Dm2_forward_2,...
          B_1_backward_2,B_2_backward_2,Cm2_backward_2, Dm2_backward_2));
    Hz_repres(ir) = Hz_repres(ir) +...
              k_0 * sum(dq_simp.* field__ForBesselBeamRepresentation_Continues_discreteRepr('Hz', typeOfCylinder,...
                  rho(ir), q, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0,...
          a_p_field_1_forw, a_p_field_1_back, a_p_field_2_forw, a_p_field_2_back,...
          psi_forward_1, psi_backward_1, psi_forward_1_transp, psi_backward_1_transp,...
          psi_forward_2, psi_backward_2, psi_forward_2_transp, psi_backward_2_transp,...
          B_1_forward_1,B_2_forward_1,Cm2_forward_1,  Dm2_forward_1,...
          B_1_backward_1,B_2_backward_1,Cm2_backward_1, Dm2_backward_1,...
          B_1_forward_2,B_2_forward_2,Cm2_forward_2,  Dm2_forward_2,...
          B_1_backward_2,B_2_backward_2,Cm2_backward_2, Dm2_backward_2));
    Ephi_repres(ir) = Ephi_repres(ir) +...
              k_0 * sum(dq_simp.* field__ForBesselBeamRepresentation_Continues_discreteRepr('Ephi', typeOfCylinder,...
                  rho(ir), q, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0,...
          a_p_field_1_forw, a_p_field_1_back, a_p_field_2_forw, a_p_field_2_back,...
          psi_forward_1, psi_backward_1, psi_forward_1_transp, psi_backward_1_transp,...
          psi_forward_2, psi_backward_2, psi_forward_2_transp, psi_backward_2_transp,...
          B_1_forward_1,B_2_forward_1,Cm2_forward_1,  Dm2_forward_1,...
          B_1_backward_1,B_2_backward_1,Cm2_backward_1, Dm2_backward_1,...
          B_1_forward_2,B_2_forward_2,Cm2_forward_2,  Dm2_forward_2,...
          B_1_backward_2,B_2_backward_2,Cm2_backward_2, Dm2_backward_2));
              
    Hphi_repres(ir) = Hphi_repres(ir) +...
              k_0 * sum(dq_simp.* field__ForBesselBeamRepresentation_Continues_discreteRepr('Hphi', typeOfCylinder,...
                  rho(ir), q, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0,...
          a_p_field_1_forw, a_p_field_1_back, a_p_field_2_forw, a_p_field_2_back,...
          psi_forward_1, psi_backward_1, psi_forward_1_transp, psi_backward_1_transp,...
          psi_forward_2, psi_backward_2, psi_forward_2_transp, psi_backward_2_transp,...
          B_1_forward_1,B_2_forward_1,Cm2_forward_1,  Dm2_forward_1,...
          B_1_backward_1,B_2_backward_1,Cm2_backward_1, Dm2_backward_1,...
          B_1_forward_2,B_2_forward_2,Cm2_forward_2,  Dm2_forward_2,...
          B_1_backward_2,B_2_backward_2,Cm2_backward_2, Dm2_backward_2));
    Erho_repres(ir) = Erho_repres(ir) +...
              k_0 * sum(dq_simp.* field__ForBesselBeamRepresentation_Continues_discreteRepr('Erho', typeOfCylinder,...
                  rho(ir), q, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0,...
          a_p_field_1_forw, a_p_field_1_back, a_p_field_2_forw, a_p_field_2_back,...
          psi_forward_1, psi_backward_1, psi_forward_1_transp, psi_backward_1_transp,...
          psi_forward_2, psi_backward_2, psi_forward_2_transp, psi_backward_2_transp,...
          B_1_forward_1,B_2_forward_1,Cm2_forward_1,  Dm2_forward_1,...
          B_1_backward_1,B_2_backward_1,Cm2_backward_1, Dm2_backward_1,...
          B_1_forward_2,B_2_forward_2,Cm2_forward_2,  Dm2_forward_2,...
          B_1_backward_2,B_2_backward_2,Cm2_backward_2, Dm2_backward_2));
    Hrho_repres(ir) = Hrho_repres(ir)  +...
              k_0 * sum(dq_simp.* field__ForBesselBeamRepresentation_Continues_discreteRepr('Hrho', typeOfCylinder,...
                  rho(ir), q, q_0, k_0, k_0, a_0, EE1, GG1, HH1, MU1, EE2, MU2, EE, MU, m, z, AE_0, AH_0,...
          a_p_field_1_forw, a_p_field_1_back, a_p_field_2_forw, a_p_field_2_back,...
          psi_forward_1, psi_backward_1, psi_forward_1_transp, psi_backward_1_transp,...
          psi_forward_2, psi_backward_2, psi_forward_2_transp, psi_backward_2_transp,...
          B_1_forward_1,B_2_forward_1,Cm2_forward_1,  Dm2_forward_1,...
          B_1_backward_1,B_2_backward_1,Cm2_backward_1, Dm2_backward_1,...
          B_1_forward_2,B_2_forward_2,Cm2_forward_2,  Dm2_forward_2,...
          B_1_backward_2,B_2_backward_2,Cm2_backward_2, Dm2_backward_2));

end
% Ez_repres(rho < a_0) = Ez_repres(rho < a_0)./ HH1;

plot_all_field_components(3, rho, a_0, '*-', 1, Ez_repres, Ephi_repres, Erho_repres, Hz_repres, Hphi_repres, Hrho_repres)


toc
