% -------------------------------------------------------------------
%  Generated by MATLAB on 19-Feb-2020 08:50:57
%  MATLAB version: 8.6.0.267246 (R2015b)
% -------------------------------------------------------------------
% saveVarsMat = load('p_n_losses.mat');
saveVarsMat = load('disperson_losses_m1_.mat');

p_n_real = saveVarsMat.p_; 
p_n_imag = saveVarsMat.p__;
Nu_e_vec = saveVarsMat.Qpts;

clear saveVarsMat;
